openapi: "3.0.0"
info:
  version: 1.0.0
  title: Account Service
servers:
  - url: http://api.audibene.local/v1
paths:
  /account/{type}:
    get:
      summary: List all accounts of a given type
      operationId: listAccounts
      parameters:
        - name: type
          in: path
          required: true
          description: The type of the account
          schema:
            type: string
      responses:
        200:
          description: An array of accounts of the given type
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Accounts"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Creates an account
      operationId: createsAccount
      parameters:
        - name: type
          in: path
          required: true
          description: The type of the account
          schema:
            type: string
      responses:
        201:
          description: The created object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Updates an account
      operationId: updatedAccount
      parameters:
        - name: type
          in: path
          required: true
          description: The type of the account
          schema:
            type: string
      responses:
        200:
          description: The updated object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Invalidates an account
      operationId: invalidateAccount
      parameters:
        - name: type
          in: path
          required: true
          description: The type of the account
          schema:
            type: string
      responses:
        204:
          description: No content
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /account/{type}/{id}:
    get:
      summary: Fetch a specific account of the given type
      operationId: fetchAccountById
      parameters:
        - name: type
          in: path
          required: true
          description: The type of the account
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: The id of the account
          schema:
            type: string
      responses:
        200:
          description: The account of the given type
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Account:
      required:
        - id
        - name
        - type
      properties:
        id:
          type: string
          format: guid
        name:
          type: string
        type:
          type: string
    Accounts:
      type: array
      items:
        $ref: "#/components/schemas/Account"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

